config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  resources :entries, only: [:create, :destroy, :show, :index]
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_list_entries.html.erb
<div id="list-entries">
  <% @entries.each do |e| %>
    <div class="entry-details">
      <%= gravatar_for e.user, size: 30 %>
      <%= link_to e.user.name, user_path(e.user) %>
      <p class="timestamp">
        Posted <%= time_ago_in_words(e.created_at) %> ago.
        <% if logged_in? && (current_user?(e.user) || current_user.admin?) %>
          <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"), e, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </p>
      <h3><%= link_to e.title, entry_path(e) %></h3>
    </div>
  <% end %>
  <%= will_paginate @entries %>
</div>

app/views/shared/_list_users.html.erb
<div>
  <% @users.each do |user| %>
    <%= gravatar_for user %>
    <%= link_to user.name, user_path(user) %>
    <% if logged_in? && current_user.admin? && !current_user?(user) %>
      <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"), user, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
    <hr>
  <% end %>
  <%= will_paginate %>
</div>

app/views/shared/_user_info.html.erb
<div id="userinfo">
  <div id="username">
    <%= gravatar_for @user %>
    <span><%= link_to @user.name, @user %></span>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p><%= link_to "#{@user.entries.count} entries", @user %></p>
    </div>
    <div class="col-md-4">
      <p><%= link_to "#{@user.following.count} following", following_user_path(@user) %></p>
    </div>
    <div class="col-md-4">
      <p id="followers"><%= link_to "#{@user.followers.count} followers", followers_user_path(@user) %></p>
    </div>
  </div>
  <div id="follow_form"><%= render 'users/follow_form' if logged_in? %></div>
</div>